#! /bin/bash

# Build pages for github deployment
source _build_client github

if [[ $? == 0 ]]; then

  echo -e """ \033[32m
===========================
DEPLOYING BUNDLES TO GITHUB
=========================== \033[0m
"""

  # Use `angular-cli-ghpages` package to do some deployment magic
  # N.b. this required setting `build.options.outputPath` to just `dist` in `angular.json`
  ./node_modules/.bin/ngh --branch gh-pages --dir dist-github

  echo -e """ \033[32m
==========================================================
Done. Your page has been deployed to:\033[36m
https://"$GITHUB_USER_NAME".github.io/"$GITHUB_REPO_NAME"/ \033[32m
========================================================== \033[0m
"""

fi
