#! /bin/bash

# Get variable $invoke_url
source _invoke_url_export

# Test post route to lambda function!
# This url must be obtained from 'invoke' url in the aws api-gateway console:
# AWS Console > Amazon API GAteway > [Name of API; default is 'las'] > Stages > POST
url=$invoke_url/contact

#
# Overwrite environment.ts file:
#
cat >src/client/environments/environment.ts <<EOL
// This file can be replaced during build by using the \$(fileReplacements) array.
// \$(ng build --prod) replaces \$(environment.ts) with \$(environment.prod.ts).
// The list of file replacements can be found in \$(angular.json).

export const environment = {
  production: false,
  emailerEndpoint: '${invoke_url}'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as \$(zone.run), \$(zoneDelegate.invokeTask).
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
EOL

#
# Overwrite environment.prod.ts file:
#
cat >src/client/environments/environment.prod.ts <<EOL
export const environment = {
  production: true,
  emailerEndpoint: '${invoke_url}'
};
EOL
